CREATE TABLE CITY (
    CITY_OID BIGSERIAL PRIMARY KEY,
    CITY_NAME VARCHAR(100)
);

CREATE TABLE LOCATION (
    LOCATION_OID BIGSERIAL PRIMARY KEY,
    LOCATION_NAME VARCHAR(100),
    CITY_OID BIGSERIAL REFERENCES CITY(CITY_OID)

);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_OID BIGSERIAL PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100),
    DEPARTMENT_EMAIL VARCHAR(255),
    LOCATION_OID BIGSERIAL REFERENCES LOCATION(LOCATION_OID)

);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_OID BIGSERIAL PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(100),
    EMPLOYEE_EMAIL VARCHAR(255),
    DEPARTMENT_OID BIGSERIAL REFERENCES DEPARTMENT(DEPARTMENT_OID)

);
